# Generated by Django 5.1.7 on 2025-05-07 23:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_comment'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='h1',
        ),
    ]
