# Generated by Django 5.1.7 on 2025-05-08 16:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0004_remove_post_h1'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
