# Generated by Django 5.1.7 on 2025-04-20 23:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='image',
            field=models.ImageField(default='post_images/default.png', upload_to='post_images/'),
        ),
    ]
